spring:
  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      mode: always
  #      data-locations: data.sql
  #      schema-locations: schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  logging:
    level:
      ROOT: ERROR

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

server:
  port: 9001